
services:
  docs-ext-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=admin
      - TZ=UTC
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - docs_ext_es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  docs_ext_es_data: