
services:
  docs-ext-kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: docs-ext-kibana
    depends_on:
      - docs-ext-elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://docs-ext-elasticsearch:9200
      - XPACK_SECURITY_ENABLED=true
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=admin
      - TZ=UTC
    restart: unless-stopped