
services:
  docs-ext-minio:
    image: minio/minio:latest
    container_name: docs-ext-minio
    ports:
      - "9000:9000"     # Porta principal (API S3)
      - "9001:9001"     # Porta da interface web (Console Admin)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - docs_ext_minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]
    restart: unless-stopped

volumes:
  docs_ext_minio_data: