spring:
  application:
    name: documentos-extrator-texto
#  elasticsearch:
#    uris: http://localhost:9200
#    username: elastic
#    password: admin

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: documentos-dsv

tika:
  url: http://localhost:9998/tika

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: ${OPEN_API_ENABLE:true}